# fly.toml app configuration file generated for shackelford-dev on 2023-10-18T19:43:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shackelford-dev"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
